os: linux

language: python

python:
  - 3.8

services:
  - docker

before_script: pip install docker-compose

install:
  - pip install -r requirements-dev.txt

scripts:
  - docker-compose -f docker-compose.yml build
  - docker-compose -f docker-compose.yml up
  - python -m unittest discover

branches:
  only:
    - master