os: linux

language: python

python:
  - 3.8

services:
  - docker

before_script:
  - pip install docker-compose
  - pip install -r requirements-dev.txt
  - docker-compose -f docker-compose.yml up --build -d


script:
  - docker-compose run --rm app sh -c "python -m unittest discover"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ttris117/flask-api:latest
  - docker-compose -f docker-compose.yml down

branches:
  only:
    - master
