os: linux

language: python

python:
  - 3.8

services:
  - docker

before_script:
  - pip install docker-compose
  - pip install -r requirements-dev.txt
  - docker-compose -f docker-compose.yml build
  - docker-compose -f docker-compose.yml up

scripts:
  - docker-compose -f run unittest tests.test

after_script:
  - docker-compose -f docker-compose.yml down

branches:
  only:
    - master